### ISSUE TITLE
Create a logo

### ISSUE THREAD

**Issue by PabRod** [julia-lang-amsterdam/julia-lang-amsterdam.github.io#6]
The current logo:

![](https://avatars.githubusercontent.com/u/162509939?s=200&v=4)

is not great.

**Comment by abelsiqueira** [comment]
5 options:

![8](https://github.com/julia-lang-amsterdam/julia-lang-amsterdam.github.io/assets/1068752/c261d019-8eb3-4326-9496-575d80bd2de2)
![7](https://github.com/julia-lang-amsterdam/julia-lang-amsterdam.github.io/assets/1068752/b5914d1c-cbb6-43a5-ae82-494027cd8f53)
![6](https://github.com/julia-lang-amsterdam/julia-lang-amsterdam.github.io/assets/1068752/6fc2db00-3803-4b93-82a8-ae759ab4790b)
![5](https://github.com/julia-lang-amsterdam/julia-lang-amsterdam.github.io/assets/1068752/08b38592-329a-477f-a6d2-2bc6f93bc1b0)
![4](https://github.com/julia-lang-amsterdam/julia-lang-amsterdam.github.io/assets/1068752/52513965-ad15-4345-90cd-d1272c44d0e7)

**Comment by PabRod** [comment]
I like the second most:

![](https://private-user-images.githubusercontent.com/1068752/312598635-b5914d1c-cbb6-43a5-ae82-494027cd8f53.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzNjkwODIsIm5iZiI6MTcxMTM2ODc4MiwicGF0aCI6Ii8xMDY4NzUyLzMxMjU5ODYzNS1iNTkxNGQxYy1jYmI2LTQzYTUtYWU4Mi00OTQwMjdjZDhmNTMuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjVUMTIxMzAyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWQxMGExM2VhMWU0NGYwN2Y0YmZmOWY1MjgxZDUyZjkwNTkzY2QyMDJiNjBlOWU2NGM2Mzk3YjNhNzExODBmOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.jzTAXvSjZR3DpWkRhk6ZYpBrCZz481ZeKUc81dHnmnE)

Do you have the `svg`? I may like to perform some tiny adjustments.

**Comment by abelsiqueira** [comment]
No image shows up in the comment. I don't have a svg of images, unfortunately.

**Comment by PabRod** [comment]
Strange. Hope it renders now. Otherwise, I mean the second one.

**Comment by abelsiqueira** [comment]
Updated with the second logo. In the future we can invest in a proper logo with SVG.
